on: [ push ]

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    name: Compile & Test SDK
            - uses: actions/cache@v2
            name: Cargo Cache
            with:
              path: |
                ~/.cargo/registry
                ~/.cargo/git
                target
              key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ env.rust_version }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cargo Cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sdk/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_version }}
      - name: Cargo Test
        run: cargo test
        working-directory: sdk